### ISSUE TITLE
Caffe package working

### ISSUE THREAD

**Issue by lemonsqueeze** [DavidEGrayson/mingw-packages-deg#1]
Hi,

Just wanted to say thanks for your mingw-w64-caffe package. Few days ago I found myself on a quest to get caffe working on msys2 and that was a big help to get started.

Somehow managed to fix the dynamic library build, as well as an issue with open() when loading trained weights, plus some of the latest boost headers are messed up and interfere with caffe. Ended up being a lot more hellish than i thought, but it works now as far as i can tell. My changes are in [mingw-caffe](https://github.com/lemonsqueeze/mingw-caffe) in case you're interested.

**Comment by DavidEGrayson** [comment]
Cool, I'm not really interested but you might submit a pull request to AlexPux/MINGW-packages and see if he wants to add it to MSYS2.
